USE_LAYOUT: True
USE_TABLE_SEGMENTATION: False
TF:
   LAYOUT:
      WEIGHTS: layout/model-800000_inf_only.data-00000-of-00001
      FILTER:
   CELL:
      WEIGHTS: cell/model-1800000_inf_only.data-00000-of-00001
      FILTER:
   ITEM:
      WEIGHTS: item/model-1620000_inf_only.data-00000-of-00001
      FILTER:
PT:
   LAYOUT:
      WEIGHTS: layout/d2_model_0829999_layout_inf_only.pt
      FILTER:
      PAD:
        TOP: 60
        RIGHT: 60
        BOTTOM: 60
        LEFT: 60
   ITEM:
     WEIGHTS: item/d2_model_1639999_item_inf_only.pt
     FILTER:
     PAD:
        TOP: 60
        RIGHT: 60
        BOTTOM: 60
        LEFT: 60
   CELL:
      WEIGHTS: cell/d2_model_1849999_cell_inf_only.pt
      FILTER:
SEGMENTATION:
  ASSIGNMENT_RULE: iou
  THRESHOLD_ROWS: 0.9
  THRESHOLD_COLS: 1.0
  FULL_TABLE_TILING: False
  REMOVE_IOU_THRESHOLD_ROWS: 0.9
  REMOVE_IOU_THRESHOLD_COLS: 1.0
  STRETCH_RULE: equal
  USE_REFINEMENT: True
USE_TABLE_REFINEMENT: False
USE_PDF_MINER: False
USE_OCR: True
OCR:
  USE_TESSERACT: False
  USE_DOCTR: True
  USE_TEXTRACT: False
  CONFIG:
    TESSERACT: dd/conf_tesseract.yaml
  WEIGHTS:
    DOCTR_WORD:
      TF: doctr/db_resnet50/tf/db_resnet50-adcafc63.zip
      PT: doctr/db_resnet50/pt/db_resnet50-ac60cadc.pt
    DOCTR_RECOGNITION:
      TF: doctr/crnn_vgg16_bn/tf/crnn_vgg16_bn-76b7f2c6.zip
      PT: doctr/crnn_vgg16_bn/pt/crnn_vgg16_bn-9762b0b0.pt
WORD_MATCHING:
  PARENTAL_CATEGORIES:
    - text
    - title
  CHILD_CATEGORIES:
    - word
  RULE: ioa
  THRESHOLD: 0.4
  MAX_PARENT_ONLY: True
TEXT_ORDERING:
  TEXT_BLOCK_CATEGORIES:
    - word
    - title
    - text
  FLOATING_TEXT_BLOCK_CATEGORIES:
    - title
    - text
  INCLUDE_RESIDUAL_TEXT_CONTAINER: True
  STARTING_POINT_TOLERANCE: 0.005
  BROKEN_LINE_TOLERANCE: 0.003
  HEIGHT_TOLERANCE: 2.0
  PARAGRAPH_BREAK: 0.035
